version = 1

test_patterns = ["tests/*Test.php"]

exclude_patterns = [
  ".github/**",
  "bootstrap/**",
  "resources/**"
]

[[analyzers]]
name = "php"

  [analyzers.meta]
  skip_doc_coverage = ["class", "magic"]

[[transformers]]
name = "php-cs-fixer"